### ISSUE TITLE
Add the quickstart guide to techhub

### ISSUE THREAD

**Issue by marcospereira** [playframework/play-java-grpc-example#14]

**Comment by ignasi35** [comment]
This is done in ~two~ _three_ steps:

 * https://github.com/lightbend/techhub/pull/240
 * https://github.com/lightbend/example-code-service/pull/149
 * (edited) https://github.com/lightbend/techhub-landing-page/pull/169

**Comment by ignasi35** [comment]
Solved in 

    lightbend/techhub#240
    lightbend/example-code-service#149
